sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t vyeruva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vyeruva/docker-react npm run test